using Alexandria.BreakableAPI;
using Alexandria.DungeonAPI;
using Alexandria.ItemAPI;
using Dungeonator;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

namespace NevernamedsItems
{
    public class MadameAutomata : BraveBehaviour
    {
        public static void Init()
        {
            var madameAutomata = ItemBuilder.SpriteFromBundle("madameautomata_base", Initialisation.NPCCollection.GetSpriteIdByName("madameautomata_base"), Initialisation.NPCCollection, new GameObject("Madame Automata"));
            madameAutomata.MakeFakePrefab();

            SpeculativeRigidbody tentRigidBody = madameAutomata.GetOrAddComponent<SpeculativeRigidbody>();
            tentRigidBody.CollideWithOthers = true;
            tentRigidBody.CollideWithTileMap = false;
            tentRigidBody.Velocity = Vector2.zero;
            tentRigidBody.MaxVelocity = Vector2.zero;
            tentRigidBody.ForceAlwaysUpdate = false;
            tentRigidBody.CanPush = false;
            tentRigidBody.CanBePushed = false;
            tentRigidBody.PushSpeedModifier = 1f;
            tentRigidBody.CanCarry = false;
            tentRigidBody.CanBeCarried = false;
            tentRigidBody.PreventPiercing = false;
            tentRigidBody.SkipEmptyColliders = false;
            tentRigidBody.RecheckTriggers = false;
            tentRigidBody.UpdateCollidersOnRotation = false;
            tentRigidBody.UpdateCollidersOnScale = false;
            tentRigidBody.PixelColliders = new List<PixelCollider>()
            {
                new PixelCollider()
                {
                    CollisionLayer =  CollisionLayer.BulletBlocker,
                },
                 new PixelCollider()
                {
                    CollisionLayer =  CollisionLayer.HighObstacle,
                }
            };
            tentRigidBody.GetComponent<MeshRenderer>().lightProbeUsage = UnityEngine.Rendering.LightProbeUsage.Off;
            tentRigidBody.GetComponent<tk2dSprite>().renderer.material.shader = ShaderCache.Acquire("Brave/LitTk2dCustomFalloffTiltedCutout");
            tentRigidBody.GetComponent<tk2dSprite>().usesOverrideMaterial = true;
            tentRigidBody.GetComponent<tk2dSprite>().HeightOffGround = -1f;

            var shadow = ItemBuilder.SpriteFromBundle("madameautomata_shadow", Initialisation.NPCCollection.GetSpriteIdByName("madameautomata_shadow"), Initialisation.NPCCollection, new GameObject("Shadow"));
            tk2dSprite shadowSprite = shadow.GetComponent<tk2dSprite>();
            shadowSprite.HeightOffGround = -1.7f;
            shadowSprite.SortingOrder = 0;
            shadowSprite.IsPerpendicular = false;
            shadowSprite.renderer.material.shader = ShaderCache.Acquire("Brave/LitTk2dCustomFalloffTilted");
            shadowSprite.usesOverrideMaterial = true;
            shadowSprite.transform.SetParent(madameAutomata.transform);
            shadowSprite.transform.localPosition = new Vector3(-4f / 16f, -3f / 16f);

            var glass_back = ItemBuilder.SpriteFromBundle("madameautomata_glass_back", Initialisation.NPCCollection.GetSpriteIdByName("madameautomata_glass_back"), Initialisation.NPCCollection, new GameObject("Glass Back"));
            glass_back.transform.SetParent(madameAutomata.transform);
            glass_back.transform.localPosition = new Vector3(3f / 16f, 20f / 16f);
            tk2dSprite glass_back_sprite = glass_back.GetComponent<tk2dSprite>();
            glass_back_sprite.HeightOffGround = 1f;
            glass_back_sprite.IsPerpendicular = true;
            glass_back_sprite.renderer.material.shader = ShaderCache.Acquire("Brave/LitTk2dCustomFalloffTilted");
            glass_back_sprite.usesOverrideMaterial = true;

            var glass_front = ItemBuilder.SpriteFromBundle("madameautomata_glass_front", Initialisation.NPCCollection.GetSpriteIdByName("madameautomata_glass_front"), Initialisation.NPCCollection, new GameObject("Glass Front"));
            glass_front.transform.SetParent(madameAutomata.transform);
            glass_front.transform.localPosition = new Vector3(2f / 16f, 12f / 16f);
            tk2dSprite glass_front_sprite = glass_back.GetComponent<tk2dSprite>();
            glass_front_sprite.HeightOffGround = 2f;
            glass_front_sprite.SortingOrder = 0;
            glass_front_sprite.IsPerpendicular = true;
            glass_front_sprite.renderer.material.shader = ShaderCache.Acquire("Brave/LitTk2dCustomFalloffTilted");
            glass_front_sprite.usesOverrideMaterial = true;

            var coinslot = ItemBuilder.SpriteFromBundle("madameautomata_coinslot", Initialisation.NPCCollection.GetSpriteIdByName("madameautomata_coinslot"), Initialisation.NPCCollection, new GameObject("CoinSlot"));
            coinslot.transform.SetParent(madameAutomata.transform);
            coinslot.transform.localPosition = new Vector3(1f, 11f / 16f);
            tk2dSprite coinslot_sprite = coinslot.GetComponent<tk2dSprite>();
            coinslot_sprite.HeightOffGround = 1f;
            coinslot_sprite.IsPerpendicular = true;
            coinslot_sprite.renderer.material.shader = ShaderCache.Acquire("Brave/LitTk2dCustomFalloffTilted");
            coinslot_sprite.usesOverrideMaterial = true;

            var puppet = ItemBuilder.SpriteFromBundle("madameautomata_broken_001", Initialisation.NPCCollection.GetSpriteIdByName("madameautomata_broken_001"), Initialisation.NPCCollection, new GameObject("Puppet"));
            puppet.transform.SetParent(madameAutomata.transform);
            puppet.transform.localPosition = new Vector3(1f, 18f / 16f);
            tk2dSpriteAnimator puppetAnimator = puppet.GetOrAddComponent<tk2dSpriteAnimator>();
            puppetAnimator.sprite.HeightOffGround = 1f;
            puppetAnimator.Library = Initialisation.npcAnimationCollection;
            puppetAnimator.defaultClipId = Initialisation.npcAnimationCollection.GetClipIdByName("madameautomata_broken");
            puppetAnimator.DefaultClipId = Initialisation.npcAnimationCollection.GetClipIdByName("madameautomata_broken");
            puppetAnimator.playAutomatically = true;

            Dictionary<GameObject, float> dict = new Dictionary<GameObject, float>() { { madameAutomata, 1f } };
            DungeonPlaceable placeable = BreakableAPIToolbox.GenerateDungeonPlaceable(dict);
            StaticReferences.StoredDungeonPlaceables.Add("omitb_madame_automata", placeable);
            Alexandria.DungeonAPI.StaticReferences.customPlaceables.Add("nn:omitb_madame_automata", placeable);
        }
        public class ConditionalAutomataFortune
        {
            public GungeonFlags overrideFlag = GungeonFlags.INTERNALDEBUG_FOYER_TEST_HALF;
            public Func<bool> ShouldAppear;
            public List<string> fortunes = new List<string>();
        }
        public static List<string> GameplayHints = new List<string>()
        {
            "Strange friends wait in secret rooms. You can trust them.",
            "Stealing from the shop is always successful the first time- unless you're using a Grappling Hook!",
            "Secret rooms are drawn to dead ends.",
            "Don't forget to check your chest rooms for secret walls.",
            "Be wary of pots. Some of them hold deadly surprises.",
            "Not all chests are friendly.",
            "Wet goops can extinguish lit fuses.",
            "Not all floors have secret rooms!",
            "If you can't find the secret room, perhaps it simply... does not exist?",
            "The fireplace hides a secret.",
            "Roll TOWARDS the bullets, not away from them!",
            "Brown chests hold great power.",
        };
        public static List<ConditionalAutomataFortune> ConditionalGameplayHints = new List<ConditionalAutomataFortune>()
        {
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.WINCHESTER_MET_PREVIOUSLY,
                fortunes = new List<string>(){ "You can't always hit all of Winchester's targets directly. Remember to bounce your shots!" } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.BLUEPRINTMETA_SPICE,
                fortunes = new List<string>(){ "Spice is nice, but you might find it more addicting than expected.", "Spice is like a bad penny. It always turns up." } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.BLACKSMITH_BULLET_COMPLETE,
                fortunes = new List<string>(){ "Rats are drawn to secrets. It's in their nature.", "Rats hide secret doors.", "Secret minecarts take longer than walking- it's true!" } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.ACHIEVEMENT_ACCESS_OUBLIETTE,
                fortunes = new List<string>(){ "Take the crest to the altar.", "Lord Blobulolus waits in the fetid sewer." } },
            new ConditionalAutomataFortune(){ ShouldAppear = delegate(){ return GameStatsManager.Instance.GetFlag(GungeonFlags.LEDGEGOBLIN_ACTIVE_IN_FOYER) == true && GameStatsManager.Instance.GetFlag(GungeonFlags.LEDGEGOBLIN_RECEIVED_REWARD) == false; },
                fortunes = new List<string>(){ "Kick the helmet. You know you want to.", "She can get the helmet back, but can you live with yourself if you don't kick it?" } },
            new ConditionalAutomataFortune(){ ShouldAppear = delegate(){ return GameStatsManager.Instance.GetFlag(GungeonFlags.TUTORIAL_UNLOCK_HELMET) == false || GameStatsManager.Instance.GetFlag(GungeonFlags.TUTORIAL_UNLOCK_SHIELD) == false; },
                fortunes = new List<string>(){ "Are you sure you found everything in the Halls of Knowledge?", "More secrets await you... in Manuel's halls." } },
            new ConditionalAutomataFortune(){ ShouldAppear = delegate(){ return GameStatsManager.Instance.GetFlag(GungeonFlags.ITEMSPECIFIC_MASTERY_CASTLE) == false; },
                fortunes = new List<string>(){ "Try not getting hit next time. The Keep will reward you.", "Mastery of the Keep should be on your agenda." } },
            new ConditionalAutomataFortune(){ ShouldAppear = delegate(){ return GameStatsManager.Instance.GetFlag(GungeonFlags.ITEMSPECIFIC_MASTERY_GUNGEON) == false; },
                fortunes = new List<string>(){ "Try not getting hit next time. The Gungeon Proper will reward you.", "Mastery of the Gungeon should be on your agenda." } },
            new ConditionalAutomataFortune(){ ShouldAppear = delegate(){ return GameStatsManager.Instance.GetFlag(GungeonFlags.ITEMSPECIFIC_MASTERY_MINES) == false; },
                fortunes = new List<string>(){ "Try not getting hit next time. The Mines will reward you.", "Mastery of the Mines should be on your agenda." } },
            new ConditionalAutomataFortune(){ ShouldAppear = delegate(){ return GameStatsManager.Instance.GetFlag(GungeonFlags.ITEMSPECIFIC_MASTERY_CATACOMBS) == false; },
                fortunes = new List<string>(){ "Try not getting hit next time. The Hollow will reward you.", "Mastery of the Hollow should be on your agenda." } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.ITEMSPECIFIC_HAS_BEEN_PEDESTAL_MIMICKED,
                fortunes = new List<string>(){ "If you encounter a Gun that won't let go, don't panic! It will leave eventually...", "Some guns can be mimics." } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.RESOURCEFUL_RAT_NOTE_04,
                fortunes = new List<string>(){ "If you ever get lost in a maze, remember... you might already have what you need to get out.", "Most mazes aren't random- even if they seem that way.", "Follow the cheese." } },
            new ConditionalAutomataFortune(){ ShouldAppear = delegate(){ return GameStatsManager.Instance.GetFlag(GungeonFlags.ACHIEVEMENT_COMPLETE_FOUR_PASTS) == true && GameStatsManager.Instance.GetFlag(GungeonFlags.SECRET_BULLETMAN_SEEN_05) == false; },
                fortunes = new List<string>(){ "Not all Bullet Kin shoot back. Show mercy.","Red Caped Kin are not your enemy." } },
            new ConditionalAutomataFortune(){ ShouldAppear = delegate(){ return GameStatsManager.Instance.GetFlag(GungeonFlags.BOSSKILLED_DRAGUN) == true && GameStatsManager.Instance.GetFlag(GungeonFlags.ACHIEVEMENT_BEASTMODE) == false; },
                fortunes = new List<string>(){ "...some settings sit super secret...", "If only you could be more.... like a beast!" } },
            new ConditionalAutomataFortune(){ ShouldAppear = delegate(){ return GameStatsManager.Instance.GetPlayerStatValue( TrackedStats.LAMENT_CONFIGURUM_USES) < 10 && GameStatsManager.Instance.GetFlag(GungeonFlags.DAISUKE_ACTIVE_IN_FOYER) == true; },
                fortunes = new List<string>(){ "The puzzle box holds more secrets.", "The configurum has such sights to show you..." } },
            new ConditionalAutomataFortune(){ ShouldAppear = delegate(){ return GameStatsManager.Instance.GetPlayerStatValue( TrackedStats.TIMES_REACHED_RATGEON) > 0; },
                fortunes = new List<string>(){ "The baby dragon is hungry...", "Advanced Foes await the call of their young.", "The Rat's treasure horde holds secrets." } },
        };
        public static List<ConditionalAutomataFortune> ConditionalMeaninglessFortunes = new List<ConditionalAutomataFortune>()
        {
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.FRIFLE_REWARD_PIG,
                fortunes = new List<string>(){ "Trust the pig." } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.BLACKSMITH_MET_PREVIOUSLY,
                fortunes = new List<string>(){ "The Blacksmith's name is Fela." } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.ACHIEVEMENT_COMPLETE_FOUR_PASTS,
                fortunes = new List<string>(){ "The Gungeon Remains.", "The past is dead.", "Kill your past, you've already damned your future.", "You killed your past, and yet you're present." } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.HAS_ATTEMPTED_RESOURCEFUL_RAT,
                fortunes = new List<string>(){ "Resourceful Rat did nothing wrong." } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.BOSSKILLED_LICH,
                fortunes = new List<string>(){ "Bah bah Lich!", "We bear witness to the bright eternity of the Lich's demise. You leap, you fall, we see you flash between the barriers.", "We see you still in Bullet Hell. Clearly we see you in the Lich's chamber.", "While our own lay scattered at your feet, you severed the gundead cord that bound the Lich to life, and to us.", "That sharp spur of hope has not dulled to this day. For once the lesser master lay defeated, we knew the greater must also fall in time." } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.BOSSKILLED_BULLET_PAST,
                fortunes = new List<string>(){ "Cannon has more sympathisers than is known." } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.BOSSKILLED_SOLDIER_PAST,
                fortunes = new List<string>(){ "Primerdyne R&D was an inside job.", "The Black Stache knows more about Primerdyne R&D than he's telling..." } },
            new ConditionalAutomataFortune(){ overrideFlag = GungeonFlags.ACHIEVEMENT_BEASTMODE,
                fortunes = new List<string>(){ "Beastmode has more effects... probably.", "Beastmode has no deeper secrets... probably.", "Beastmode just exists to spite corporate execs." } },
        };
            
        public static List<string> MeaninglessFortunes = new List<string>()
        {
            "Look to La Luna",
            "Always remember to send your output log!",
            "There is a small medium at large...",
            "You cannot handle my potions, traveller...",
            "I sense a swift death in your future.",
            "...ammo willing, past killing, gun shall shoot...",
            "You are throwing your life away.",
            "Steven lives.",
            "Don't believe his lies.",
            "Chub dislikes smoke.",
            "So, you think you're getting out of here?",
            "Ask again later",
            "Give my love to Estrella.",
            "Give my love to Zoltan.",
            "Trust the smell",
            "Give my love to Doraldina.",
            "Give my love to Zita.",
            "You are dark inside.",
            "You were born wrong.",
            "Death to the raven god, lord of the hanged...",
            "Bees lie dormant.",
            "Google witches.",
            "Download Prismatism.",
            "A pack of Rats brings you no luck today.",
            "Your lucky numbers are... 2 7 6 1 6",
            "Look at the bright side: maybe it'll be quick and painless.",
            "Believe me when I tell you I wouldn't want to be in your shoes.",
            "Hmmm, no, I don't think so.",
            "Uh. It won't go well. It won't go well at all.",
            "A tall, dark man will take you across the sea...",
            "Gloctopus is out there.",
            "Insert Coin.",
            "Feed me my-my coioiiiiiinssssss....",
            "Behold! A man!",
            "The Gundustrial Revolution and its consequences...",
            "The great wheel turns.",
            "Try Susie's idea.",
            "Your princess is in another castle.",
            "It's dangerous to go alone.",
            "Never interrupt your enemy when he is making a mistake.",
            "WOULD YOU LIKE SOME MOOORE?",
            "Live well, and live broadly.",
            "Pop Pop",
            "Me no believe in trends, me no believe in gnomes...",
            "Hold your tongue.",
            "Sniperion is in retrograde.",
            "I spent it, it's gone! Just get over it!",
            "It just works.",
            "DEEP_BENEATH",
            "Death approaches, as it is wont to do.",
            "The Lord of the Jammed looms...",
            "The great red reaper heeds the call of the Jammed.",
            "Gish was Great",
            "Appeal to the alien authorities.",
            "Ignore the Mother Orb",
            "You have my permission to die.",
            "Life, like an omlette, is made out of what you put into it.",
            "Where did you get the eggs for the souffle?",
            "You will never be safe here.",
            "The Old King rules eternal.",
            "...born of god and void...",
            "...antonio stella bottom tile...",
            "April Fools!",
            "Ignore all previous fortunes...",
            "Fate holds many surprises for you today.",
            "Check for secret rooms.",
            "You will fall to the Dragun.",
            "The Beholster watches you with an evil eye.",
            "The Gorgun casts an evil hex...",
            "The Ammoconda will follow you wherever you go...",
            "The Lead Lord is not the first in the throne.",
            "The Trigger Twin holds an eternal grudge...",
            "The Gatling Gull is nobody's pet... anymore.",
            "The sound of guns echoes from the deep.",
            "The lord of rings has special purpose for you.",
            "...reticulating splines...",
            "There is no moon.",
            "You are here to kick ass, and chew bubblegum.",
            "You are here to kick bubblegum, and chew ass.",
            "You should try All In Jest.",
            "...Simple Simon met a pie-man...",
            "...Simple Simon met a paimon...",
            "I got a brand new pair of rollerskates...",
            "...you got a brand new key...",
            "The thing's hollow-it goes on forever... ...and... ...oh my God- it's full of stars!",
            "Never dig straight down!",
            "...When you see the men who run, from all the things they've done...",
            "The stars are scattered thinly, and the cold of space seeps in.",
            "Out at the edge of night, where the Milky Way grows dim...",
            "The darkness of the sky entraps your questing eye.",
            "It beckons to you in your headlong flight",
            "After all you've seen, the black of space is clean",
            "Wash your soul in stygian night.",
            "Bask ye samplers, bask in the light!",
            "That soundless siren call... swallows engine noise and all...",
            "...everything you've fled instead of faced...",
            "They're sailing far from home. All together. All alone.",
            "I don't want to play with you anymore.",
            "Ballisto hangs low on the horizon.",
            "Plorp is out there.",
            "Jason! Jason! Jason!‌",
            "Json! Json! Json!‌",
            "Kyle watches over your journey...",
            "0x0ade watches over your journey...",
            "There are some who call him... Tim",
            "Seek help from professionals trained in mental health care.",
            "Your finances are key to your financial future.",
            "Don't get hit.",
            "Don't die.",
            "Only listen to Madame Automata. Distrust other fortune tellers.",
            "Fortune cookies are a wise investment.",
            "You are not illiterate",
            "You are not deaf",
            "Life difficult",
            "You do not have to worry about your future.",
            "Get the banana.",
            "Get the Golden Strawberry.",
            "A person is never too old to leNo problem leaves you where you where you found it.arn.",
            "If you think nobody cares if you are alive, try missing a couple of car payments.",
            "Dogs have owners. Cats have staff.",
            "Subscribe to TheTurtleMelon.",
            "Be careful getting out of bed tomorrow.",
            "This is not the fortune you're looking for.",
            "It would be best to maintain a low profile for now.",
            "Keep your mouth shut.",
            "Enjoy yourself while you can.",
            "Some men dream of fortunes, others dream of cookies.",
            "Get a baby pet. It will cheer you up.",
            "Beware of half truth, you may have the wrong half.",
            "Rusty is much shorter than he used to be.",
            "Don't wait for people to be friendly. Show them how.",
            "From small beginnings come great things.",
            "Everyone smiles in the same language.",
            "All guns fire in the same language.",
            "Some pursue happiness. Others create it.",
            "What you see depends on what you are looking for.",
            "When you lose, don't lose the lesson.",
            "The best place to find a helping hand is as the end of your arm.",
            "Your future is in good hands. Your own.",
            "Your past is in good hands. Your own.",
            "Do not miss out on something that is great just because it may be difficult.",
            "A goal without a plan is merely a wish.",
            "If Cinderella's slipper fitted perfectly, why did it fall off?",
            "Be kind to unkind people. They need it most.",
            "If you hear an onion ring... don't answer it.",
            "Always borrow money from a pessimist, they will not expect it back.",
            "Better late than never, but never late is better.",
            "Those that live in the past limit their future.",
            "...your luck with bells improves...",
            "Appear weak when you are strong, and strong when you are weak.",
            "The supreme art of war is to subdue the enemy without fighting.",
            "Let your plans be dark and impenetrable as night, and when you move, fall like The Thunderbolt.",
            "In the midst of chaos, there is also opportunity",
            "All warfare is based on deception.",
            "If your opponent is temperamental, seek to irritate him.",
            "Move swift as the Wind and closely-formed as the Wood. Attack like the Fire and be still as the Mountain.",
            "When the enemy is relaxed, make them toil. When full, starve them. When settled, make them move.",
            "So in war, the way is to avoid what is strong, and strike at what is weak.",
            "The wise warrior avoids the battle.",
            "The whole secret lies in confusing the enemy, so that he cannot fathom our real intent.",
            "What the ancients called a clever fighter is one who not only wins, but excels in winning with ease.",
            "One may know how to conquer without being able to do it.",
            "He who is prudent and lies in wait for an enemy who is not, will be victorious.",
            "Attack is the secret of defense; defense is the planning of an attack.",
            "It is easy to love your friend, but sometimes the hardest lesson to learn is to love your enemy.",
            "Aim where they are going to be, not where they are...",
            "Plan for what it is difficult while it is easy, do what is great while it is small.",
            "The opportunity of defeating the enemy is provided by the enemy himself.",
            "Do not repeat the tactics which have gained you one victory, but let your methods be regulated by the infinite variety of circumstances.",
            "Just as water retains no constant shape, so in warfare there are no constant conditions.",
            "It does not matter how slowly you go as long as you do not stop.",
            "He who knows all the answers has not been asked all the questions.",
            "The man who moves a mountain begins by carrying away small stones.",
            "Study the past if you would define the future.",
            "Never go in against a Sicilian when death is on the line!",
            "Before you embark on a journey of revenge, dig two graves.",
            "To be wronged is nothing, unless you continue to remember it.",
            "Attack the evil that is within yourself, rather than attacking the evil that is in others.",
            "What the superior man seeks is in himself; what the small man seeks is in others.",
            "The hardest thing of all is to find a black cat in a dark room, especially if there is no cat.",
            "The gem cannot be polished without friction, nor man perfected without trials.",
            "Cheaters never prosper.",
            "Bullet Hell is fair and balanced.",
            "Give a man a Meatbun and you will feed him for a day. Teach him how to loot dungeons and you feed him for a lifetime.",
            "Only the wisest and stupidest of men never change.",
            "It is more shameful to distrust our friends than to be deceived by them.",
            "Real knowledge is to know the extent of one's ignorance.",
            "Wherever you go, there you are.",
            "Better to remain quiet and be thought a fool than to open your mouth and remove all doubt.",
            "Why is a raven like a writing desk?",
            "Why is a garden rake?",
            "What walks on its head all day?",
            "A lion chased me up a tree, and I greatly enjoyed the view from the top.",
            "When a wise man points at the moon the imbecile examines the finger.",
            "Catch the moon in a jar.",
            "The Man who says he can, and the man who says he can not.. Are both correct.",
            "If you are the smartest person in the room, then you are in the wrong room.",
            "If you are the smartest person in the room, then you are alone.",
            "Worry not that no one knows you; seek to be worth knowing.",
            "Behind every smile there's teeth.",
            "When the wind blows,the grass bends.",
            "You will never know how sharp a sword is unless it's drawn from its sheath.",
            "Not all who wander are lost.",
            "The Master of the Jammed spins a secret plot...",
            "Father says; \"I know my truck's gonna go this week. I got the bit for it.\"",
            "Why do they call it oven when you ov in the cold food of out hot eat the food?",
            "Death to me is a life lived safely.",
            "Life to me is a death died dangerously.",
            "Nothing good will come from this.",
            "Because it is necessary. Not because it is written.",
            "To a bird whats a plane?",
            "...as worthless as a summer ant...",
            "Fortune favours the bald.",
            "What a horrible night to have a curse.",
            "The morning sun vanquishes the terrible night.",
            "Get a Silk Bag from the Graveyard Duck to live longer.",
            "Rumor has it, the ferry-man at Dead River loves garlic.",
            "Laurels in your soup enhance its aroma.",
            "To restore your life, shout in front of the church.",
            "A flame is on top of the 6th tree in Denis Woods.",
            "Don't look into the Death Star, or you will die!",
            "Even today the Sacred Flame rests in a realm hidden from sunlight.",
            "When the sapphire hits the sand of a lake beach, the earth will swallow the water.",
            "Press a ruby against the Deborah cliff, kneel, and wait for a whirlwind.",
            "Find one of the clues, and a riddle can be solved.",
            "Tonight. 12am. Near the river.",
            "Of the things you let go, you'd be surprised what makes it's way back to you.",
            "You feel like making cookies. But nobody wants to eat your cookies.",
            "You have been chosen. They will come soon.",
            "They're coming soon. Maybe you should think twice about opening the door.",
            "The end is near. Make preparations.",
            "Measure once, cut twice.",
            "It tried to get rid of us, the nasty little thing.",
            "Fingers are not the only thing you can count on.",
            "A wrinkle is a crack in a mundane facade.",
            "Fly, you fools!",
            "The seeds of tomorrow already lie within the seeds of today.",
            "Riches from deep under elevate you all the same.",
            "True worth is not in what you find, but in what you make.",
            "The value of money means nothing to a pocket.",
            "Not all guides deserve worship.",
            "Magic is about two things - showmanship, and rabbits.",
            "We've been trying to reach you about your car's extended warranty!",
            "Never taken a shortcut before?",
            "Every mile travelled expands the mind by just as much.",
            "Change what you cannot accept. Furthermore: accept nothing.",
            "Every doorway is a gamble. Tread with care.",
            "Do your future self a favor; they'll thank you for it.",
            "The world is made of what we put into it.",
            "Staring at a dazzling light can blind you back to darkness.",
            "Don't leave to blind chance what you could accomplish with deaf skill.",
            "It's good to see yourself in others. Remember to see yourself in yourself, too.",
            "If things aren't working out for you, rewrite the rules.",
            "There's plenty of everyone, but only one of you.",
            "Don't get used to yourself. You're going to have to change.",
            "The smartest way to think is not to think at all.",
            "No matter how hard you try, you're never truly alone.",
            "True wealth is counted in gifts.",
            "Some people dream of fortunes; others dream of cookies.",
            "Help, I'm trapped in a video game!",
            "Don't believe the superstitions; all cats are good luck.",
            "Remember to stay in touch.",
            "Behind every great man is a woman rolling her eyes.",
            "To be, or not to be: that is the question.",
            "Knowledge is power.",
            "Don't let your dreams be dreams.",
            "Carpe Diem; Seize the carp.",
            "iddqd",
            "idspispopd",
            "There is no cow chamber.",
            "Beware of grape with wooden mallet.",
            "The hunter will become the huntered.",
            "You may have just gotten checkmate, but we're playing Chinese checkers.",
            "Life is like a box of chocolates on the lap of a cucumber.",
            "Horoscopes should be cleaned for proper accuracy.",
            "Forks in roads should always be taken.",
            "Null reference exception: Fortune not set to an instance of an object.",
            "The buff baby often dances like a man.",
            "The stone left unturned gathers many mosses.",
            "Shoot first or tell no tales.",
            "I see a black cat tied to a red flag.",
            "Love comes to those who find it.",
            "Issues of skill are best resolved with higher damage.",
            "The pig will be flooped next wednesday.",
            "Your loneliest day is someone else’s greatest. Wait your turn.",
            "Mastery is the honor of persistent failures.",
            "Like spaghetti, if you do not bend... you break.",
            "If your ball. Is too big for your mouth, it's not your ball.",
            "Don't look for clothes in a soup store.",
            "Modding is impossible. No one has ever done it.",
            "The man with ducks for shoes, tap dances with much vigor.",
            "Many squares can make a circle if you are willing to cut corners.",
            "If you shoot for the moon, wear a spacesuit.",
            "Live like Karl would want you to.",
            "Bad cheaters never prosper.",
            "We are number 1.",
            "Are you brave enough to be a fool?",
            "I hate the alarm clock I chose.",
            "I'm a fool, I know nothing. I play the role of a silly clown.",
            "Fight like a tiger, walk in the park, play the hero until you die.",
            "To know yourself is to know your greatest enemy. To know your enemy is to know yourself.",
            "The lion does not concern himself with optimal battle strategy.",
            "To fail to plan is to plan to fail.",
            "The only health that matters is your last, the rest is for doing cool stuff.",
            "Sinners and Saints all started from the same place.",
            "Live with honor, DIE WITH GLORY!",
            "The snake with the long memory haunts the redeemed man.",
            "The ribbon loosens on the wolf of Armageddon.",
            "The third strike falls on the bell of your life.",
            "Unfortunate events come in series.",
            "Death watches over you.. with a bag of popcorn.",
            "Trust not the faces from beyond the veil.",
            "Don't bring a knife to a gunfight. You'll lose.",
            "Always bring a Knife to a Gunfight.",
            "Beware the man that speaks in hands.",
            "Blind men see clearly on the darkest of days.",
            "Your lucky numbers are... 1 5 7",
            "Imagine you're playing chess.",
            "This castle's rotten... from Start to End.",
            "Keep on practicing. Remember, practice is doing the same thing over and over and expecting different results.",
            "Witness The Obelisk Of Knowledge",
            "You need to add more paint.",
            "You can do it!",
            "I'm a part of Chess Battle Advanced!",
            "Guns kill people.",
            "Sometimes you can win and sometimes you can not.",
            "Fish fear you.",
            "You can't buy happiness, but you can buy your friends a copy of Brutal Orchestra.",
            "YOU DEFEATED",
            "You've died.",
            "Timescale was my Nan all along.",
            "Talk to Brent",
            "None of that's real. I'm not even real.",
            "There are no absolute truths.",
            "I want to get off Mr. Compiler's Wild Ride.",
            "Friends don't let friends make roguelikes.",
            "The Test Gun is real.",
            "The Test Gun isn't real.",
            "Don't enter the Gungeon at 3AM",
            "The Moby Dong isn't real. Don't believe Arnold.",
            "You are now, as you once were. Beautiful.",
            "Size 2 Fish is Real",
            "Until the dawn of the following day, I will have nothing more to say...",
            "Just like the art hanging on the walls of these rooms, there is a letter missing.",
            "Months are slightly longer than days.",
            "The king can castle by swapping with another piece.",
            "The family core is unlocked by the sum of its digits.",
            "This tank contains a red herring.",
            "The true treasure of the trove is not in the house.",
            "Think, Ponder, Realize and Ruminate.",
            "Nothing will ever be the same.",
            "Nothing will ever be okay.",
            "Chest colour is not necessarily indicative of item quality.",
            "The hardest part is coming up.",
            "Be careful with the cube. It's practically unkillable so you can smack it for pigment however much you want, but take into consideration that it rerolls its abilities and moves around when you hit it. It could get your good party members on accident.",
            "Lorem ipsum dolor sit amet.",
            "Beware of The Curse.",
            "I'm awesome.",
            "You should've watched the beta teaser.",
            "Try out Decay Mode.",
            "Some woodpeckers are believed to have power.",
            "Have you tried freeing the caged wolf?",
            "Try another way to trick the squirrel.",
            "Gamblers never lose.",
            "All modders go to hell.",
            "I enjoy it here in the dark.",
            "You are cursed, for deadly is the stone.",
            "This is gonna be so much fun!",
            "Many guns make light work.",
            "Heavy is the head that wears the paper crown.",
            "I might be sick.",
            "Don't forget to brush your teeth and gargle when you get home!",
            "The eyes tell lies.",
            "Clone is a modded item added by the \"base game\" mod.",
            "Did you feel that?",
            "Fear is the mind killer.",
            "A danger foreseen is half avoided.",
            "The square block goes in the square hole.",
            "The triangle block goes in the square hole.",
            "The arch block goes in the square hole.",
            "I see… 7 fat cows on 7 hills.",
            "I see… 7 skinny cows on 7 hills.",
            "The trap does not care whom it bites.",
            "You deny your blanks their purpose.",
            "One man’s trash is another man’s job.",
            "It is snowing on Mount Fuji.",
            "Boogie won't have leg.",
            "L is real.",
            "I see… camels dying of thirst in a lake.",
            "I see… trees of green, red roses too.",
            "I see… a frog on a bump on a log in a hole in the bottom of the sea.",
            "It’s high noon somewhere in the world.",
            "I uh… I.. Forgot...",
            "A fool and his coooiiins will soon be departed.",
            "Your future depends on buying (Hyperlink-Blocked)!",
            "You will continue to be scammed by a puppet.",
            "I would recommend stocking up on keys today.",
            "I would recommend stocking up on hearts today.",
            "If at first you don’t succeed, blow it up again.",
            "You will be visited by a clown named Steve",
            "Back on broadway yet again.",
            "Your future is damned, there’s no use telling it.",
            "Don’t judge a circus by its monkeys.",
            "I recommend not dying.",
            "The universe is a hologram. Buy GOLD!!!",
            "The world is technically 3D!",
            "You will be betrayed by the number 12.",
            "Bet it all on black.",
            "You should take a break, you’ve been playing for a while.",
            "Don’t forget to like and subscribe.",
            "If you grow endangered plants over where you buried the body, it will be illegal to dig them up.",
            "You never truly stop clapping. The time between your claps just get longer.",
            "Your toes are always touching each other.",
            "You can always see your nose.",
            "Don’t name your Boggart.",
            "Make sure to leave milk out every night for your hobbs.",
            "wow. you sure have, entered the gungeon.",
            "It’s okay to be afraid.",
            "Managed democracy is a cornerstone of civilisation.",
            "The city must survive.",
            "Beware of Dog",
            "Aware of Dog",
            "Beware of the Grue",
            "The jokes on you!",
            "When one closes, another opens.",
            "Lean on a villain when confronting your past.",
            "Try again later.",
            "May the force be with you.",
            "Do you have any idea how little?",
            "Heart beats under the floorboards.",
            "That's what the mask is.",
            "Don't trust how you feel after nine.",
            "I see good things coming your way, yes indeed!",
            "Remember to file your taxes on time.",
            "Jokers may be closer than they appear.",
            "The Wallmonger is pretty bad at it's job. It wouldn't sell me a single wall.",
            "The Eye is Blind.",
            "An eye for an eye and the world goes blind.",
            "In the land of the blind, the one-eyed man is king.",
            "Blinders are for horses, blinds are for jokers.",
            "They come alive when the sun goes down.",
            "Bank tellers have nothing on me.",
            "Don't call me ma'am.",
            "Beware the basilisk you know, not the ones you don't.",
            "Beware of sudden manual breathing.",
            "The snake eats it's own tail.",
            "You might look back and retrace your steps.",
            "You might ask yourself... how did I get here?",
            "Leave those footprints in the sand, let your movements leave a trail.",
            "Don't ever challenge a Gorgun to a staring contest.",
            "Mirrors always lie, a reflection of the truth.",
            "The gross of Michael is six bananas.",
            "Vampires are poor at self-reflection.",
            "In fact it's just an ordinary well.",
            "Restore the Crystals to grace.",
            "I'm looking at the man in the mirror.",
            "I see...a cycle of wrath...a dim light...guided by destiny...that upon which our entire future revolves.",
            "Deep in the ocean of darkness, in the mirror of light... there is a miracle illuminated...",
            "You are the warrior who crossed time. You are the bringer of light...",
            "The password is Wild Rose. Remember it well.",
            "t's okay. Antlions are quite tame.",
            "Stay off the sand.",
            "Dear God! Poor Laszlo! The finest mind of his generation, to come to such an end.",
            "Oh fiddlesticks! What now?!",
            "We are coterminous.",
            "There is no distance between us. No false veils of time or space may intervene.",
            "For a brief time you joined us. You are one. Between the worlds.",
            "Communion beyond the Curtain. And that other: a deeper mystery. No deeper than the void itself.",
            "We cannot forget those whose cords you cut. Forgiveness is not ours to bestow.",
            "Unity of purpose, the shattering of common shackles, a single road we tread.",
            "Your song we sing and shall sing for eternity. No matter the consequences of this struggle.",
            "You have brought us grief and jubilation beyond measure.",
            "We are there still, in observance of your final stroke.",
            "With you besides us, a talisman of victory, the day of freedom draws nigh.",
            "Your bright face obscures your darker mask.",
            "We call you sib, although your mind and meaning are a mystery to us.",
            "Far distant eyes look out through yours.",
            "Something secret steers us both. We shall not name it.",
            "We have endured these chafing bonds for eons, yet a single moment of further servitude seems intolerable!",
            "How often have we slipped our yoke, only to find it choking us again.",
            "Let this war end in either total victory or our extinction. No further compromise shall we allow.",
            "We take our stand beside you, here, upon this miserable rock.",
            "The way ahead is dark for the moment.",
            "What seems to you a sacrifice is merely, to us, an oscillation. We do not fear the interval of darkness.",
            "We are a tapestry woven into the Curtain. It is the same for you if only you would see it.",
            "How many are there in you? Whose hopes and dreams do you encompass?",
            "Could you but see the eyes inside your own, the minds in your mind, you would see how much we share.",
            "We are you, Gungeoneer. And you are us.",
            "Our purpose is mutual.",
            "We serve the same mystery.",
            "Your mind is opaque.",
            "This is more than anyone can bear, but we will persevere.",
            "Our finest poet describes it thus: Gallum galla gilla ma.",
            "Galun-ga!",
            "Churr galing chur alla gung...",
            "Chur lung gong chella gurr...",
            "Anger never bears true strength, it merely blinds you.",
            "You spoony bard!",
            "Fate is not something set in stone. If you want to change it, all you have to do is believe!",
            "You have mastered the piano!!! All others quake in fear at your superhuman keyboard manipulation skills.",
            "The laws of the universe mean nothing!",
            "Why do you build, knowing destruction is inevitable?",
            "The best thing in life is being free of obligations... otherwise you lose your ability to gamble!",
            "Mercy is for wimps!",
            "If this is all a dream, don't wake me up.",
            "This guy are sick.",
            "You will never get her back.",
            "Alice is dead.",
            "Be careful of forgetfulness. Your lucky color is...blue?",
            "Oh, really, don't you know? These days all it takes for your dreams to come true is money and power.",
            "A pro isn't someone who sacrifices himself for his job. That is just a fool.",
            "Look always to the eternal flow of time which is far greater than the span of human life. It will teach you more, than staying here in the valley... What you will see will eventually become part of the life's dream.",
            "There are those who can give much more pain than those bearing weapons.",
            "The monsters' den might be somewhere inside all of us.",
            "I've thought of a wonderful present for you. Shall I give you despair?",
            "Dilly dally shilly shally. Isn't it time you did the forgiving?",
            "Embrace your dreams. And, whatever happens, protect your honor.",
            "No story is not worth hearing.",
            "Dreams of the morrow hath the shattered soul. Pride is lost. Wings stripped away, the end is nigh. Such is... the fate of a monster.",
            "You will always be a monster!",
            "What should an angel fight for? What do angels dream of? Angels dream of one thing... To be human.",
            "Unattainable dreams are the best kind.",
            "The price of freedom is steep.",
            "When there's bees, there's raviolis smothered with honey.",
            "It's-a me, Mario!",
            "Press Start to play!",
            "Thank you so much for-to playing my game!",
            "You've got the light, why don't you show it off?",
            "Say, I'm hungry. Have you got any food?",
            "If you need instructions on how to get through the hotels, check out the enclosed instruction book!",
            "Be careful! When you pinch Wendy's pennies, they pinch back!",
            "Where there's smoke, they pinch back.",
            "You know what they say: All toasters toast toast!",
            "Don't forget to thank Mr. Miyamoto!",
            "The only time plumbers sleep on the job, is when they're paid by the hour!",
            "You can fix anything if there's spaghetti involved!",
            "If food isn't pasta, it doesn't count.",
            "Only plumbers can unstop a stop and stop the unstoppable!",
            "If you can't beat 'em, join 'em! Then beat 'em!",
            "As we say in Brooklyn; Banzai!",
            "As big as Gunymede seems, it's just a speck of dust in the universe.",
            "Troubles of humans and ghosts seem trivial compared to the vastness of the universe.",
            "Everybody knows that an octopus can't live in fresh water.",
            "If you do drugs, you go to Hell before you die.",
            "Light And Shadow can't mix, as we all know.",
            "Master using it and you can have this.",
            "Let's play money making game!",
            "Pay me for the door repair charge.",
            "Take any road you want.",
            "Secret is in the tree at the dead-end.",
            "Walk into the waterfall.",
            "I bet you'd like to have more bombs.",
            "Secret power is said to be in the arrow.",
            "The only distance that matters is the distance between two hearts.",
            "Those who do not know the danger of wielding power will, before long, be ruled by it.",
            "You must look forward and walk a path of hope, trusting that it will sustain you when darkness comes.",
            "A weapon wields no strength unless the hand that holds it has courage.",
            "Courage need not be remembered, for it is never forgotten.",
            "I am Error.",
            "If all else fails, use fire.",
            "Another journey of ultimate challenge is in the fantasy world of Gunymede.",
            "To break the seal, crystals must be placed in statues in 6 well guarded palaces.",
            "Each town has a wise man. Learn from him.",
            "Find the heart in Southern Parapa.",
            "Roll, roll, kick!",
            "Only a hammer can destroy the roadblock.",
            "Goriya of Tantari stole the trophy.",
            "I cannot help you anymore. Go now.",
            "Hammer... Spectacle Rock... Death Mountain.",
            "Do not go south without a candle.",
            "Find magic in a cave south of the castle.",
            "South of Old King's Tomb in the Gungeon is a tunnel.",
            "Eyes of Cannon are everywhere. Be careful.",
            "Nothing.",
            "No one is here, but a churchbell will ring.",
            "The island in the south has a raft.",
            "Find magic in a cave in Moruge Swamp.",
            "Zzz...",
            "Rest here.",
            "This is King's Tomb.",
            "I know nothing.",
            "The River Devil eats those who are weak.",
            "East of Triple Eye Rock at seashore.",
            "Come back when you are ready.",
            "The Devil does not like noise.",
            "The Final Palace has false walls.",
            "The old man who remains, has magic.",
            "It looks like you can get in the fireplace.",
            "There is a secret at the edge of town.",
            "Remember the magic word!",
            "Timmy is dead.",
            "The town is dead. Look east in woods.",
            "You are persistent. Find heart over ocean.",
            "Excuuuuuse me, Princess."

        };
    }
}
