using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SaveAPI
{
    public enum CustomDungeonFlags
    {
        //Add your custom flags here
        //You can remove any flags here (except NONE, don't remove it)
        NONE,
        //---------------------------------------------Task Based Unlocks
        PLAYERHELDMORETHANFIVEARMOUR,
        KILLEDJAMMEDKEYBULLETKIN,
        KILLEDJAMMEDCHANCEKIN,
        KILLEDJAMMEDMIMIC,
        HASBEENDAMAGEDBYRISKRIFLE,
        FAILEDRATMAZE,
        USEDFALLENANGELSHRINE,
        KILLEDENEMYWITHTHROWNGUN,
        USED_FALSE_BLANK_TEN_TIMES,
        KILLED_TITAN_KIN,
        HAS_BEATEN_BOSS_BY_SKIN_OF_TEETH,
        BEATEN_ANY_BOSS_TURBO_MODE,
        BEATEN_MINES_BOSS_TURBO_MODE,
        BEATEN_HOLLOW_BOSS_TURBO_MODE,
        KILLED_DRAGUN_WITH_DOG,
        ANGERED_BELLO,
        RAINBOW_KILLED_LICH,
        ROBOT_HELD_FIVE_JUNK,
        //---------------------------------------------Shop Based Dummy Unlocks
        //DOUG
        PURCHASED_LOCKDOWNBULLETS,
        PURCHASED_THETHINLINE,
        PURCHASED_NITROBULLETS,
        PURCHASED_KINAMMOLET,
        PURCHASED_SHUTDOWNSHELLS,
        PURCHASED_ERRORSHELLS,
        PURCHASED_MEATSHIELD,
        PURCHASED_MAGICMISSILE,
        PURCHASED_MINERSBULLETS,
        PURCHASED_RANDOROUNDS,
        //TRORC
        PURCHASED_TRACERROUNDS,
        PURCHASED_BAZOOKA,
        PURCHASED_ANTIMATERIELRIFLE,
        PURCHASED_RIOTGUN,
        PURCHASED_UNENGRAVEDBULLETS,
        PURCHASED_SPRINGLOADEDCHAMBER,
        //GOOPTON
        PURCHASED_GRACEFULGOOP,
        PURCHASED_GOOMPERORSCROWN,
        PURCHASED_VACUUMGUN,
        PURCHASED_ALKALIBULLETS,
        PURCHASED_VISCERIFLE,
        PURCHASED_LIQUIDMETALBODY,
        PURCHASED_LOVEPOTION,
        PURCHASED_SPEEDPOTION,
        PURCHASED_SANCTIFIEDOIL,
        PURCHASED_SNAILBULLETS,
        PURCHASED_SPORELAUNCHER,
        //CADENCE AND OX
        PURCHASED_RISKRIFLE,
        PURCHASED_CREDITOR,
        PURCHASED_OVERPRICEDHEADBAND,
        PURCHASED_POWERARMOUR,
        PURCHASED_RECYCLINDER,
        PURCHASED_BLASMASTER,
        PURCHASED_DARTRIFLE,
        PURCHASED_DEMOLITIONIST,
        PURCHASED_REPEATOVOLVER,
        PURCHASED_SPIRAL,
        PURCHASED_STUNGUN,
        PURCHASED_DRONE
    }
}
